[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32H743ZITx --connect-under-reset"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"
