on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "13 3 * * 2"

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      # setting this overrides environment variables used for linking
      # RUSTFLAGS: "-D warnings"
      DEFMT_LOG: "debug"
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
      - run: cargo build --target thumbv7em-none-eabihf

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          components: clippy
          target: thumbv7em-none-eabihf
      # not using clippy-check due to this issue:
      # https://github.com/actions-rs/clippy-check/issues/2
      - run: cargo clippy -- --deny warnings

  format:
    name: Format
    runs-on: ubuntu-latest
    env: {"RUSTFLAGS": "-D warnings"}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo +nightly fmt -- --check
